---

docker_url: https://download.docker.com/linux

docker_version: "5:28.1.1-1"

packages_for_docker:
 - ca-certificates
 - curl

docker_packages:
 - docker-ce={{ docker_version }}
 - docker-ce-cli={{ docker_version }}
 - containerd.io
 - docker-buildx-plugin
 - docker-compose
 - docker-compose-plugin
