---

- name: Query packages installed in the distribution
  ansible.builtin.package_facts:
    manager: auto

- name: Create a user '{{ user }}'
  ansible.builtin.user:
    name: '{{ user }}'
    shell: /bin/bash
    create_home: yes

- name: Add '{{ user }}' in docker
  ansible.builtin.user:
    name: '{{ user }}'
    groups: docker
  when: " 'docker-ce' and 'docker-compose' in ansible_facts.packages"

